### ISSUE TITLE
dialog_image模型的chinese_gpt_original指的是什么模型？

### ISSUE THREAD

**Issue by LinglingGreat** [silverriver/MMChat#3]
如题，能不能给个模型链接

**Comment by silverriver** [comment]
我更新了Readme，添加了下载链接：

The pre-trained `chinese_gpt_original` model used in our experiments can be downloaded from [Baidu Netdisk](https://pan.baidu.com/s/1l_jLVcpBnGXpLp7yf3lqiw) with extract code of `nmoc`, or downloaded from [Google Drive](https://drive.google.com/drive/folders/1rwWv7gbWQrxDMCOr5fpqVd0jJQF4NQu0?usp=sharing).

其实这个模型来自于之前我们另外一个工作（https://github.com/silverriver/Stylized_Dialog）
